plugins {
    id("sightline.android-application")
    id("sightline.compose")
}

android {
    namespace = "com.rextechnologies.sightline"

    defaultConfig {
        applicationId = "com.rextechnologies.sightline"
    }
}

sightline {
    // Screen branches are generated by Compose; production logic is kept in :android:core at 100%.
    appCoverageFloor(logicLine = 0.65, logicBranch = 0.50, screenLine = 0.45)
}

dependencies {
    implementation(project(":android:core"))
    implementation(project(":android:design"))
    implementation(project(":protocol"))

    implementation(platform(libs.compose.bom))
    implementation(libs.androidx.activity.compose)
    implementation(libs.compose.foundation)
    implementation(libs.compose.material3)
    implementation(libs.compose.ui)
    implementation(libs.kotlinx.coroutines.android)

    testImplementation(libs.junit)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.androidx.test.ext.junit)
    testImplementation(platform(libs.compose.bom))
    testImplementation(libs.compose.ui.test.junit4)
    debugImplementation(libs.compose.ui.test.manifest)
}
